apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tft-rolling
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        managed-by: github-actions
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: us-east1-docker.pkg.dev/tft-rolling-probability/tft-rolling/app:latest
        name: app-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      timeoutSeconds: 60
  traffic:
  - latestRevision: true
    percent: 100
